name = "AutoOffload"
uuid = "f0abef60-9ec0-11e9-27de-db6506a91768"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "0.1.0"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
